- name: "Make sure /etc/systemd/timesyncd.conf.d/ exists."
  file:
    state: "directory"
    dest: "/etc/systemd/timesyncd.conf.d/"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - "aspects_timesyncd"

- name: "Template /etc/systemd/timesyncd.conf.d/99-aspects_timesyncd.conf"
  template:
    src: "99-aspects_timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf.d/99-aspects_timesyncd.conf"
    owner: "root"
    group: "root"
    mode: "644"
  notify: "restart systemd-timesyncd"
  tags:
    - "aspects_timesyncd"